version: '3'
services:
  dbmysql:
    image: "mysql:8.0.21"
    ports:
      - "3307:3307"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=vini
      - MYSQL_DATABASE=pagamento